// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: buff.proto

// The realtime protocol for the template match engine.

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	OpCode_OPCODE_UNSPECIFIED OpCode = 0
	OpCode_OPCODE_START       OpCode = 1
	OpCode_OPCODE_ADD_CARD    OpCode = 2
	OpCode_OPCODE_ADD_BUILD   OpCode = 3
	OpCode_OPCODE_CAST_CARD   OpCode = 4
	OpCode_OPCODE_ATTACK      OpCode = 5
	OpCode_OPCODE_END_TURN    OpCode = 6
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OPCODE_UNSPECIFIED",
		1: "OPCODE_START",
		2: "OPCODE_ADD_CARD",
		3: "OPCODE_ADD_BUILD",
		4: "OPCODE_CAST_CARD",
		5: "OPCODE_ATTACK",
		6: "OPCODE_END_TURN",
	}
	OpCode_value = map[string]int32{
		"OPCODE_UNSPECIFIED": 0,
		"OPCODE_START":       1,
		"OPCODE_ADD_CARD":    2,
		"OPCODE_ADD_BUILD":   3,
		"OPCODE_CAST_CARD":   4,
		"OPCODE_ATTACK":      5,
		"OPCODE_END_TURN":    6,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_buff_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_buff_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{0}
}

// state
type Mana struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   int64 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Blue  int64 `protobuf:"varint,2,opt,name=blue,proto3" json:"blue,omitempty"`
	Green int64 `protobuf:"varint,3,opt,name=green,proto3" json:"green,omitempty"`
	White int64 `protobuf:"varint,4,opt,name=white,proto3" json:"white,omitempty"`
	Black int64 `protobuf:"varint,5,opt,name=black,proto3" json:"black,omitempty"`
}

func (x *Mana) Reset() {
	*x = Mana{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mana) ProtoMessage() {}

func (x *Mana) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mana.ProtoReflect.Descriptor instead.
func (*Mana) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{0}
}

func (x *Mana) GetRed() int64 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *Mana) GetBlue() int64 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *Mana) GetGreen() int64 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *Mana) GetWhite() int64 {
	if x != nil {
		return x.White
	}
	return 0
}

func (x *Mana) GetBlack() int64 {
	if x != nil {
		return x.Black
	}
	return 0
}

type Zone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Zone) Reset() {
	*x = Zone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{1}
}

type Spell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Spell) Reset() {
	*x = Spell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Spell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spell) ProtoMessage() {}

func (x *Spell) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spell.ProtoReflect.Descriptor instead.
func (*Spell) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{2}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{3}
}

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healty int64   `protobuf:"varint,1,opt,name=healty,proto3" json:"healty,omitempty"`
	Cost   []*Mana `protobuf:"bytes,2,rep,name=cost,proto3" json:"cost,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{4}
}

func (x *Unit) GetHealty() int64 {
	if x != nil {
		return x.Healty
	}
	return 0
}

func (x *Unit) GetCost() []*Mana {
	if x != nil {
		return x.Cost
	}
	return nil
}

type Build struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add *Mana `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	Sub *Mana `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	One *Mana `protobuf:"bytes,3,opt,name=one,proto3" json:"one,omitempty"`
}

func (x *Build) Reset() {
	*x = Build{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{5}
}

func (x *Build) GetAdd() *Mana {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Build) GetSub() *Mana {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *Build) GetOne() *Mana {
	if x != nil {
		return x.One
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// Types that are assignable to CardType:
	//
	//	*Card_Unit
	//	*Card_Build
	CardType isCard_CardType `protobuf_oneof:"card_type"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{6}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (m *Card) GetCardType() isCard_CardType {
	if m != nil {
		return m.CardType
	}
	return nil
}

func (x *Card) GetUnit() *Unit {
	if x, ok := x.GetCardType().(*Card_Unit); ok {
		return x.Unit
	}
	return nil
}

func (x *Card) GetBuild() *Build {
	if x, ok := x.GetCardType().(*Card_Build); ok {
		return x.Build
	}
	return nil
}

type isCard_CardType interface {
	isCard_CardType()
}

type Card_Unit struct {
	Unit *Unit `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

type Card_Build struct {
	Build *Build `protobuf:"bytes,5,opt,name=build,proto3,oneof"`
}

func (*Card_Unit) isCard_CardType() {}

func (*Card_Build) isCard_CardType() {}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mana  *Mana   `protobuf:"bytes,3,opt,name=mana,proto3" json:"mana,omitempty"`
	Tabel []*Card `protobuf:"bytes,5,rep,name=tabel,proto3" json:"tabel,omitempty"`
	Build []*Card `protobuf:"bytes,6,rep,name=build,proto3" json:"build,omitempty"`
	Deads []*Card `protobuf:"bytes,7,rep,name=deads,proto3" json:"deads,omitempty"`
	Hand  []*Card `protobuf:"bytes,8,rep,name=hand,proto3" json:"hand,omitempty"`
	Deck  []*Card `protobuf:"bytes,9,rep,name=deck,proto3" json:"deck,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetMana() *Mana {
	if x != nil {
		return x.Mana
	}
	return nil
}

func (x *Player) GetTabel() []*Card {
	if x != nil {
		return x.Tabel
	}
	return nil
}

func (x *Player) GetBuild() []*Card {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *Player) GetDeads() []*Card {
	if x != nil {
		return x.Deads
	}
	return nil
}

func (x *Player) GetHand() []*Card {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *Player) GetDeck() []*Card {
	if x != nil {
		return x.Deck
	}
	return nil
}

// send_data
type Enemy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mana    *Mana   `protobuf:"bytes,3,opt,name=mana,proto3" json:"mana,omitempty"`
	Tabel   []*Card `protobuf:"bytes,5,rep,name=tabel,proto3" json:"tabel,omitempty"`
	Build   []*Card `protobuf:"bytes,6,rep,name=build,proto3" json:"build,omitempty"`
	Deads   []*Card `protobuf:"bytes,7,rep,name=deads,proto3" json:"deads,omitempty"`
	HandLen int64   `protobuf:"varint,8,opt,name=hand_len,json=handLen,proto3" json:"hand_len,omitempty"`
}

func (x *Enemy) Reset() {
	*x = Enemy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Enemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enemy) ProtoMessage() {}

func (x *Enemy) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enemy.ProtoReflect.Descriptor instead.
func (*Enemy) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{8}
}

func (x *Enemy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enemy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Enemy) GetMana() *Mana {
	if x != nil {
		return x.Mana
	}
	return nil
}

func (x *Enemy) GetTabel() []*Card {
	if x != nil {
		return x.Tabel
	}
	return nil
}

func (x *Enemy) GetBuild() []*Card {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *Enemy) GetDeads() []*Card {
	if x != nil {
		return x.Deads
	}
	return nil
}

func (x *Enemy) GetHandLen() int64 {
	if x != nil {
		return x.HandLen
	}
	return 0
}

type Attack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetPlayer string `protobuf:"bytes,1,opt,name=target_player,json=targetPlayer,proto3" json:"target_player,omitempty"`
	TargetCard   string `protobuf:"bytes,2,opt,name=target_card,json=targetCard,proto3" json:"target_card,omitempty"` //from
}

func (x *Attack) Reset() {
	*x = Attack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{9}
}

func (x *Attack) GetTargetPlayer() string {
	if x != nil {
		return x.TargetPlayer
	}
	return ""
}

func (x *Attack) GetTargetCard() string {
	if x != nil {
		return x.TargetCard
	}
	return ""
}

type Cast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCard string `protobuf:"bytes,1,opt,name=target_card,json=targetCard,proto3" json:"target_card,omitempty"`
}

func (x *Cast) Reset() {
	*x = Cast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{10}
}

func (x *Cast) GetTargetCard() string {
	if x != nil {
		return x.TargetCard
	}
	return ""
}

var File_buff_proto protoreflect.FileDescriptor

var file_buff_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x6e, 0x0a, 0x04, 0x4d, 0x61, 0x6e, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x22, 0x06, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x53, 0x70, 0x65,
	0x6c, 0x6c, 0x22, 0x06, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x3d, 0x0a, 0x04, 0x55, 0x6e,
	0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x6f,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x61, 0x6e, 0x61, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x05, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12,
	0x1b, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x1b, 0x0a, 0x03,
	0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x04, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x00, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x42,
	0x0b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xec, 0x01, 0x0a,
	0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x6d,
	0x61, 0x6e, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x12, 0x1f, 0x0a, 0x05, 0x74, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x05,
	0x64, 0x65, 0x61, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x64, 0x65, 0x61, 0x64, 0x73, 0x12, 0x1d, 0x0a,
	0x04, 0x68, 0x61, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x68, 0x61, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x04,
	0x64, 0x65, 0x63, 0x6b, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x64, 0x65, 0x63, 0x6b, 0x22, 0xc8, 0x01, 0x0a, 0x05,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x6d, 0x61, 0x6e,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61,
	0x6e, 0x61, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x12, 0x1f, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x05, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x05, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x64, 0x65,
	0x61, 0x64, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x64, 0x65, 0x61, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x61, 0x6e, 0x64, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x68,
	0x61, 0x6e, 0x64, 0x4c, 0x65, 0x6e, 0x22, 0x4e, 0x0a, 0x06, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x2a,
	0x9b, 0x01, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x50,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x41,
	0x44, 0x44, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x43,
	0x4f, 0x44, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x10, 0x03, 0x12,
	0x14, 0x0a, 0x10, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x41, 0x53, 0x54, 0x5f, 0x43,
	0x41, 0x52, 0x44, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f,
	0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x50, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x54, 0x55, 0x52, 0x4e, 0x10, 0x06, 0x42, 0x0b, 0x5a,
	0x09, 0x6d, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_buff_proto_rawDescOnce sync.Once
	file_buff_proto_rawDescData = file_buff_proto_rawDesc
)

func file_buff_proto_rawDescGZIP() []byte {
	file_buff_proto_rawDescOnce.Do(func() {
		file_buff_proto_rawDescData = protoimpl.X.CompressGZIP(file_buff_proto_rawDescData)
	})
	return file_buff_proto_rawDescData
}

var file_buff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_buff_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_buff_proto_goTypes = []interface{}{
	(OpCode)(0),    // 0: api.OpCode
	(*Mana)(nil),   // 1: api.Mana
	(*Zone)(nil),   // 2: api.Zone
	(*Spell)(nil),  // 3: api.Spell
	(*Item)(nil),   // 4: api.Item
	(*Unit)(nil),   // 5: api.Unit
	(*Build)(nil),  // 6: api.Build
	(*Card)(nil),   // 7: api.Card
	(*Player)(nil), // 8: api.Player
	(*Enemy)(nil),  // 9: api.Enemy
	(*Attack)(nil), // 10: api.Attack
	(*Cast)(nil),   // 11: api.Cast
}
var file_buff_proto_depIdxs = []int32{
	1,  // 0: api.Unit.cost:type_name -> api.Mana
	1,  // 1: api.Build.add:type_name -> api.Mana
	1,  // 2: api.Build.sub:type_name -> api.Mana
	1,  // 3: api.Build.one:type_name -> api.Mana
	5,  // 4: api.Card.unit:type_name -> api.Unit
	6,  // 5: api.Card.build:type_name -> api.Build
	1,  // 6: api.Player.mana:type_name -> api.Mana
	7,  // 7: api.Player.tabel:type_name -> api.Card
	7,  // 8: api.Player.build:type_name -> api.Card
	7,  // 9: api.Player.deads:type_name -> api.Card
	7,  // 10: api.Player.hand:type_name -> api.Card
	7,  // 11: api.Player.deck:type_name -> api.Card
	1,  // 12: api.Enemy.mana:type_name -> api.Mana
	7,  // 13: api.Enemy.tabel:type_name -> api.Card
	7,  // 14: api.Enemy.build:type_name -> api.Card
	7,  // 15: api.Enemy.deads:type_name -> api.Card
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_buff_proto_init() }
func file_buff_proto_init() {
	if File_buff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mana); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Spell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Build); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Enemy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_buff_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Card_Unit)(nil),
		(*Card_Build)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buff_proto_goTypes,
		DependencyIndexes: file_buff_proto_depIdxs,
		EnumInfos:         file_buff_proto_enumTypes,
		MessageInfos:      file_buff_proto_msgTypes,
	}.Build()
	File_buff_proto = out.File
	file_buff_proto_rawDesc = nil
	file_buff_proto_goTypes = nil
	file_buff_proto_depIdxs = nil
}
