// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: buff.proto

// The realtime protocol for the template match engine.

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	// No opcode specified. Unused.
	OpCode_OPCODE_UNSPECIFIED OpCode = 0
	// New game round starting.
	OpCode_OPCODE_START OpCode = 1
	// Update to the state of an ongoing round.
	OpCode_OPCODE_UPDATE OpCode = 2
	// A game round has just completed.
	OpCode_OPCODE_DONE OpCode = 3
	// A move the player wishes to make and sends to the server.
	OpCode_OPCODE_MOVE OpCode = 4
	// Move was rejected.
	OpCode_OPCODE_REJECTED OpCode = 5
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OPCODE_UNSPECIFIED",
		1: "OPCODE_START",
		2: "OPCODE_UPDATE",
		3: "OPCODE_DONE",
		4: "OPCODE_MOVE",
		5: "OPCODE_REJECTED",
	}
	OpCode_value = map[string]int32{
		"OPCODE_UNSPECIFIED": 0,
		"OPCODE_START":       1,
		"OPCODE_UPDATE":      2,
		"OPCODE_DONE":        3,
		"OPCODE_MOVE":        4,
		"OPCODE_REJECTED":    5,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_buff_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_buff_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{0}
}

type Mana struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Red   int64 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Blue  int64 `protobuf:"varint,2,opt,name=blue,proto3" json:"blue,omitempty"`
	Green int64 `protobuf:"varint,3,opt,name=green,proto3" json:"green,omitempty"`
	White int64 `protobuf:"varint,4,opt,name=white,proto3" json:"white,omitempty"`
	Black int64 `protobuf:"varint,5,opt,name=black,proto3" json:"black,omitempty"`
}

func (x *Mana) Reset() {
	*x = Mana{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mana) ProtoMessage() {}

func (x *Mana) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mana.ProtoReflect.Descriptor instead.
func (*Mana) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{0}
}

func (x *Mana) GetRed() int64 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *Mana) GetBlue() int64 {
	if x != nil {
		return x.Blue
	}
	return 0
}

func (x *Mana) GetGreen() int64 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *Mana) GetWhite() int64 {
	if x != nil {
		return x.White
	}
	return 0
}

func (x *Mana) GetBlack() int64 {
	if x != nil {
		return x.Black
	}
	return 0
}

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healty int64   `protobuf:"varint,1,opt,name=healty,proto3" json:"healty,omitempty"`
	Cost   []*Mana `protobuf:"bytes,2,rep,name=cost,proto3" json:"cost,omitempty"`
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{1}
}

func (x *Unit) GetHealty() int64 {
	if x != nil {
		return x.Healty
	}
	return 0
}

func (x *Unit) GetCost() []*Mana {
	if x != nil {
		return x.Cost
	}
	return nil
}

type Build struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add *Mana `protobuf:"bytes,1,opt,name=add,proto3" json:"add,omitempty"`
	Sub *Mana `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	One *Mana `protobuf:"bytes,3,opt,name=one,proto3" json:"one,omitempty"`
}

func (x *Build) Reset() {
	*x = Build{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{2}
}

func (x *Build) GetAdd() *Mana {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *Build) GetSub() *Mana {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *Build) GetOne() *Mana {
	if x != nil {
		return x.One
	}
	return nil
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// Types that are assignable to CardType:
	//
	//	*Card_Unit
	//	*Card_Build
	CardType isCard_CardType `protobuf_oneof:"card_type"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{3}
}

func (x *Card) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (m *Card) GetCardType() isCard_CardType {
	if m != nil {
		return m.CardType
	}
	return nil
}

func (x *Card) GetUnit() *Unit {
	if x, ok := x.GetCardType().(*Card_Unit); ok {
		return x.Unit
	}
	return nil
}

func (x *Card) GetBuild() *Build {
	if x, ok := x.GetCardType().(*Card_Build); ok {
		return x.Build
	}
	return nil
}

type isCard_CardType interface {
	isCard_CardType()
}

type Card_Unit struct {
	Unit *Unit `protobuf:"bytes,4,opt,name=unit,proto3,oneof"`
}

type Card_Build struct {
	Build *Build `protobuf:"bytes,5,opt,name=build,proto3,oneof"`
}

func (*Card_Unit) isCard_CardType() {}

func (*Card_Build) isCard_CardType() {}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mana  *Mana   `protobuf:"bytes,3,opt,name=mana,proto3" json:"mana,omitempty"`
	Tabel []*Card `protobuf:"bytes,4,rep,name=tabel,proto3" json:"tabel,omitempty"`
	Build []*Card `protobuf:"bytes,5,rep,name=build,proto3" json:"build,omitempty"`
	Deads []*Card `protobuf:"bytes,6,rep,name=deads,proto3" json:"deads,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_buff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_buff_proto_rawDescGZIP(), []int{4}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetMana() *Mana {
	if x != nil {
		return x.Mana
	}
	return nil
}

func (x *Player) GetTabel() []*Card {
	if x != nil {
		return x.Tabel
	}
	return nil
}

func (x *Player) GetBuild() []*Card {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *Player) GetDeads() []*Card {
	if x != nil {
		return x.Deads
	}
	return nil
}

var File_buff_proto protoreflect.FileDescriptor

var file_buff_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x75, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x6e, 0x0a, 0x04, 0x4d, 0x61, 0x6e, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x6c, 0x75, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x67, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x68, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x6c, 0x61, 0x63,
	0x6b, 0x22, 0x3d, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c, 0x74,
	0x79, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74,
	0x22, 0x5e, 0x0a, 0x05, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x61, 0x64, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e,
	0x61, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x03,
	0x73, 0x75, 0x62, 0x12, 0x1b, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x03, 0x6f, 0x6e, 0x65,
	0x22, 0x90, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x48, 0x00, 0x52,
	0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x6d, 0x61, 0x6e, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x52, 0x04, 0x6d, 0x61, 0x6e,
	0x61, 0x12, 0x1f, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x74, 0x61, 0x62,
	0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x05, 0x64, 0x65, 0x61, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x64,
	0x65, 0x61, 0x64, 0x73, 0x2a, 0x7c, 0x0a, 0x06, 0x4f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x12, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x50, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4f,
	0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b,
	0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x04, 0x12, 0x13, 0x0a,
	0x0f, 0x4f, 0x50, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44,
	0x10, 0x05, 0x42, 0x0b, 0x5a, 0x09, 0x6d, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buff_proto_rawDescOnce sync.Once
	file_buff_proto_rawDescData = file_buff_proto_rawDesc
)

func file_buff_proto_rawDescGZIP() []byte {
	file_buff_proto_rawDescOnce.Do(func() {
		file_buff_proto_rawDescData = protoimpl.X.CompressGZIP(file_buff_proto_rawDescData)
	})
	return file_buff_proto_rawDescData
}

var file_buff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_buff_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_buff_proto_goTypes = []interface{}{
	(OpCode)(0),    // 0: api.OpCode
	(*Mana)(nil),   // 1: api.Mana
	(*Unit)(nil),   // 2: api.Unit
	(*Build)(nil),  // 3: api.Build
	(*Card)(nil),   // 4: api.Card
	(*Player)(nil), // 5: api.Player
}
var file_buff_proto_depIdxs = []int32{
	1,  // 0: api.Unit.cost:type_name -> api.Mana
	1,  // 1: api.Build.add:type_name -> api.Mana
	1,  // 2: api.Build.sub:type_name -> api.Mana
	1,  // 3: api.Build.one:type_name -> api.Mana
	2,  // 4: api.Card.unit:type_name -> api.Unit
	3,  // 5: api.Card.build:type_name -> api.Build
	1,  // 6: api.Player.mana:type_name -> api.Mana
	4,  // 7: api.Player.tabel:type_name -> api.Card
	4,  // 8: api.Player.build:type_name -> api.Card
	4,  // 9: api.Player.deads:type_name -> api.Card
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_buff_proto_init() }
func file_buff_proto_init() {
	if File_buff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mana); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Build); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_buff_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Card_Unit)(nil),
		(*Card_Build)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buff_proto_goTypes,
		DependencyIndexes: file_buff_proto_depIdxs,
		EnumInfos:         file_buff_proto_enumTypes,
		MessageInfos:      file_buff_proto_msgTypes,
	}.Build()
	File_buff_proto = out.File
	file_buff_proto_rawDesc = nil
	file_buff_proto_goTypes = nil
	file_buff_proto_depIdxs = nil
}
